dadia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('main.profileurls')),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


urlpatterns = [
    path('', views.acara, name='Acara'),
    path('tambah-berita/', views.tambah_berita, name='Tambah Berita'),
    path('berita/<int:id>', views.detail_berita, name='Detail Berita'),
    path('berita/', views.berita, name='Berita'),
    path('acara/<int:id>/biaya-tambahan', views.biaya_tambahan, name='Biaya Tambahan'),
    path('acara/<int:id>/dana/print', views.print_dana, name='Print Dana'),
    path('acara/<int:id>/biaya-tambahan/print', views.print_biaya_tambahan, name='Print Biaya Tambahan'),
    path('acara/<int:id>/peturunan/print', views.print_peturunan, name='Print Peturunan'),
    path('acara/<int:id>/tunggakan/print', views.print_tunggakan, name='Print Tunggakan'),
    path('acara/<int:id>/dana', views.dana, name='Dana'),
    path('acara/<int:id>', views.detail_acara, name='Detail Acara'),
    path('acara/', views.acara, name='Acara'),
    path('get-jumlah/<int:id>/<int:id_peturunan>', views.get_jumlah, name='Get Jumlah'),
    path('get-dana/<int:id>', views.get_dana, name='Get Dana'),
    path('get-acara/<int:id>', views.get_acara, name='Get Acara'),
    path('hapus-dana/<int:id>', views.hapus_dana, name='Hapus Dana'),
    path('hapus-acara/<int:id>', views.hapus_acara, name='Hapus Acara'),
    path('acara/<int:id>/peturunan', views.peturunan, name='Peturunan'),
    path('get-detail-peturunan/<int:id>', views.get_detail_peturunan, name='Get Detail Peturunan'),
    path('hapus-detail-peturunan/<int:id>', views.hapus_detail_peturunan, name='Hapus Detail Peturunan'),
    path('acara/<int:id>/tunggakan', views.tunggakan, name='Tunggakan'),
    path('acara/<int:id>/validasi-bayar-transfer/', views.validasi_bayar_transfer, name='Validasi Bayar Transfer'),
    path('acara/<int:id>/validasi-pengajuan/', views.validasi_pengajuan, name='Validasi Pengajuan'),
    path('validasi-transfer/<int:id>/<int:id_acara>', views.validasi_transfer, name='Validasi Transfer'),
    path('terima-pengajuan/<int:id>/<int:id_acara>', views.terima_pengajuan, name='Terima Pengajuan'),
    path('tolak-transfer/<int:id>/<int:id_acara>', views.tolak_transfer, name='Tolak Transfer'),
    path('get-pengajuan/<int:id>', views.get_pengajuan, name='Get Pengajuan'),
    path('anggota/', views.pengguna, name='Pengguna'),
    path('hapus-anggota/<int:id>', views.hapus_anggota, name='Hapus Anggota'),
    path('get-anggota/<int:id>', views.get_anggota, name='Get Anggota'),
    path('validasi-anggota/', views.validasi_pengguna, name='Validasi Pengguna'),
    path('terima-anggota/<int:id>', views.terima_anggota, name='Terima Anggota'),
    path('kas/', views.kas, name='Kas'),
    path('get-kas/<int:id>', views.get_kas, name='Get Kas'),
    path('hapus-kas/<int:id>', views.hapus_kas, name='Hapus Kas'),
    path('acara/<int:id_acara>/usulan/<int:id>', views.detail_usulan, name='Detail Usulan'),
    path('like-usulan/<int:id>/<int:id_acara>', views.like_usulan, name='Like Usulan'),
    path('dislike-usulan/<int:id>/<int:id_acara>', views.dislike_usulan, name='Dislike Usulan'),
    path('hapus-like-usulan/<int:id>/<int:id_acara>', views.hapus_like_usulan, name='Hapus Like Usulan'),
    path('hapus-dislike-usulan/<int:id>/<int:id_acara>', views.hapus_dislike_usulan, name='Hapus Dislike Usulan'),
    path('detail-like-usulan/<int:id>/<int:id_acara>', views.detail_like_usulan, name='Detail Like Usulan'),
    path('detail-dislike-usulan/<int:id>/<int:id_acara>', views.detail_dislike_usulan, name='Detail Dislike Usulan'),
    path('hapus-detail-like-usulan/<int:id>/<int:id_acara>', views.hapus_detail_like_usulan, name='Hapus Detail Like Usulan'),
    path('hapus-detail-dislike-usulan/<int:id>/<int:id_acara>', views.hapus_detail_dislike_usulan, name='Hapus Detail Dislike Usulan'),
    path('like-comment/<int:id_acara>/<int:id_usulan>/<int:id>', views.like_comment, name='Like Comment'),
    path('dislike-comment/<int:id_acara>/<int:id_usulan>/<int:id>', views.dislike_comment, name='Dislike Comment'),
    path('hapus-like-comment/<int:id_acara>/<int:id_usulan>/<int:id>', views.hapus_like_comment, name='Hapus Like Comment'),
    path('hapus-dislike-comment/<int:id_acara>/<int:id_usulan>/<int:id>', views.hapus_dislike_comment, name='Hapus Dislike Comment'),
    path('get-notifikasi/', views.get_notifikasi, name='Get Notifikasi'),
    path('baca-notifikasi/<int:id>/', views.baca_notifikasi, name='Baca Notifikasi'),
    path('pengumuman/', views.pengumuman, name="Pengumuman"),
    path('hapus-pengumuman/<int:id>', views.hapus_pengumuman, name='Hapus Pengumuman'),
    path('get-pengumuman/<int:id>', views.get_pengumuman, name='Get Pengumuman'),
    path('print-kas/', views.print_kas, name='Print Kas'),
    path('get-berita/<int:id>', views.get_berita, name='Get Berita'),
    path('hapus-berita/<int:id>', views.hapus_berita, name='Hapus Berita'),
    path('test/', views.test, name='Test'),
    path('tutorial/', views.tutorial, name='Tutorial')
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# Create your models here.


def get_upload_path_ktp(instance, filename):
    return os.path.join("./static/documents/KTP/" + str(instance.nama), filename)


def get_upload_path_profile(instance, filename):
    return os.path.join("./static/documents/Profile/" + str(instance.nama), filename)


def get_upload_path_berita(instance, filename):
    return os.path.join("./static/documents/Berita/" + str(instance.judul), filename)


def get_upload_path_struk(instance, filename):
    return os.path.join("./static/documents/Struk/"+ str(instance.acara.judul) + '/' + str(instance.id), filename)


def get_upload_path_bukti_pembayaran(instance, filename):
    return os.path.join("./static/documents/Bukti Pembayaran/"+ str(instance.pengguna.nama) + '/' + str(instance.id), filename)


class Pengguna(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nama = models.CharField(max_length=100, blank=False)
    no_ktp = models.CharField(max_length=16, blank=True, null=True)
    no_hp = models.CharField(max_length=12, blank=True, null=True)
    status = models.BooleanField(default=False)
    alasan = models.TextField(null=True, blank=True)
    tipe = models.CharField(max_length=20, blank=False)
    foto_ktp = models.FileField(upload_to=get_upload_path_ktp, max_length=1000, blank=True, null=True)
    foto_profile = models.FileField(upload_to=get_upload_path_profile, max_length=1000, blank=True, null=True)

    def __str__(self):
        return self.nama
    

class Acara(models.Model):
    judul = models.CharField(max_length=100, blank=False)
    deskripsi = models.TextField(blank=True)
    tanggal_mulai = models.DateField(auto_now=False)
    tanggal_selesai = models.DateField(auto_now=False, blank=True)
    status_selesai = models.BooleanField(default=False)
    dibuat_oleh = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False)

    def __str__(self):
        return self.judul

    
class Dana(models.Model):
    acara = models.ForeignKey(Acara, on_delete=models.CASCADE, primary_key=False)
    tipe = models.CharField(max_length=20, blank=False)
    deskripsi = models.TextField(blank=False)
    jumlah = models.IntegerField(blank=False)
    tanggal = models.DateTimeField(auto_now=True)
    struk = models.FileField(upload_to=get_upload_path_struk, max_length=1000)

    def __str__(self):
        return str(self.id)


class Peturunan(models.Model):
    acara = models.ForeignKey(Acara, on_delete=models.CASCADE, primary_key=False)
    jumlah_peturunan = models.IntegerField(blank=False)
    jumlah_bayar_tiap_anggota = models.IntegerField(blank=True)
    tambahan_bayar = models.IntegerField(blank=True, default=0)
    batas_pembayaran = models.DateField(blank=False)

    def __str__(self):
        return str(self.id)


class TambahanPeturunan(models.Model):
    peturunan = models.ForeignKey(Peturunan, on_delete=models.CASCADE, primary_key=False)
    pengguna = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False)
    
    def __str__(self):
        return str(self.peturunan.acara.judul)


class DetailPeturunan(models.Model):
    peturunan = models.ForeignKey(Peturunan, on_delete=models.CASCADE, primary_key=False)
    pengguna = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False)
    bayar = models.IntegerField(blank=False)
    tanggal_bayar = models.DateTimeField(null=True, default=None)
    diapprove_oleh = models.ForeignKey(Pengguna, default=None, null=True, on_delete=models.CASCADE, primary_key=False, related_name='Approve')
    status = models.BooleanField(default=False)
    tanggal_approve = models.DateTimeField(default=None, null=True)
    bukti_pembayaran = models.FileField(blank=True, upload_to=get_upload_path_bukti_pembayaran, max_length=1000)
    alasan = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.id)


class Berita(models.Model):
    judul = models.TextField(blank=False)
    foto = models.FileField(upload_to=get_upload_path_berita, max_length=1000)
    deskripsi = models.TextField(blank=False)
    tanggal = models.DateTimeField(auto_now=False)
    dibuat_oleh = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False)

    def __str__(self):
        return self.judul


class Pengumuman(models.Model):
    judul = models.TextField(blank=False)
    deskripsi = models.TextField(blank=False)
    tanggal = models.DateTimeField(auto_now=False)
    dibuat_oleh = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False)

    def __str__(self):
        return str(self.id)


class Kas(models.Model):
    tipe = models.CharField(max_length=20, blank=False)
    deskripsi = models.TextField(blank=False)
    jumlah = models.IntegerField(blank=False)
    tanggal = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)


class Pengajuan(models.Model):
    acara = models.ForeignKey(Acara, on_delete=models.CASCADE, primary_key=False)
    dikirim_oleh = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False)
    deskripsi = models.TextField(blank=False)
    jumlah = models.IntegerField(blank=False)
    tanggal_kirim = models.DateTimeField(null=True, default=None)
    status = models.BooleanField(default=False)
    tanggal_diapprove = models.DateTimeField(null=True, default=None)
    diapprove_oleh = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False, null=True, blank=True, related_name='ApprovePengajuan')
    alasan = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.id)


class Usulan(models.Model):
    acara = models.ForeignKey(Acara, on_delete=models.CASCADE, primary_key=False)
    pengusul = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False)
    usulan = models.TextField(blank=False)
    tanggal = models.DateTimeField(null=True, default=None)
    like = models.IntegerField(blank=True)
    dislike = models.IntegerField(blank=True)


class LikeUsulan(models.Model):
    usulan = models.ForeignKey(Usulan, on_delete=models.CASCADE, primary_key=False)
    pengusul = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False)
    tanggal = models.DateTimeField(null=True, default=None)
    tipe = models.BooleanField(default=False)


class CommentUsulan(models.Model):
    usulan = models.ForeignKey(Usulan, on_delete=models.CASCADE, primary_key=False)
    pengusul = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False)
    usulan_comment = models.TextField(blank=False)
    tanggal = models.DateTimeField(null=True, default=None)
    like = models.IntegerField(blank=True)
    dislike = models.IntegerField(blank=True)


class LikeCommentUsulan(models.Model):
    comment_usulan = models.ForeignKey(CommentUsulan, on_delete=models.CASCADE, primary_key=False)
    pengusul = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False)
    tanggal = models.DateTimeField(null=True, default=None)
    tipe = models.BooleanField(default=False)


class Notifikasi(models.Model):
    dari = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False)
    ke = models.ForeignKey(Pengguna, on_delete=models.CASCADE, primary_key=False, related_name="dari")
    pesan = models.TextField(blank=False)
    tanggal = models.DateTimeField(null=True, default=None)
    url = models.TextField(blank=False)
    sudah_dibaca = models.BooleanField(default=False)

main/templates/main/acara.html
{% extends 'main/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
  <div class="d-flex justify-content-between">
    <h4 class="fw-bold py-3 px-4"><span class="text-muted fw-light"></span> Kegiatan / Acara</h4>
    {% if request.user.pengguna.tipe == 'Admin' %}
    <div>
      <button type="button" class="btn btn-icon btn-primary mt-2 mx-4" data-bs-toggle="modal" data-bs-target="#tambahAcara">
        <span class="tf-icons bx bxs-plus-square"></span>
      </button>
    </div>
    {% endif %}
  </div>
  {% include 'main/messages.html'%}
  <div class="row">
    {% if ada_data %}
    {% for a in acara %}
    <div class="col-md-6 col-lg-6 mb-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">{{ a.judul }}</h5>
          <p class="card-text" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">{{ a.deskripsi }}</p>
          <a href="/acara/{{ a.id }}" class="btn btn-primary">Detail</a>
        </div>
        <div class="card-footer text-muted">{{ a.tanggal_mulai }} / {{ a.tanggal_selesai }}</div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h4 align="center" class="text-danger">Belum ada acara!</h4>
    {% endif %}
  </div>
</div>
{% endblock %}
{% block modal %}
<div class="modal fade" id="tambahAcara" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tambahAcaraLabel">Tambah Acara</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form id='form' action="#" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row mb-3">
            <label class="col-sm-3 col-form-label" for="id_judul">Judul Kegiatan</label>
            <div class="col-sm-9">
              {{ form.judul }}
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-3 col-form-label" for="id_deskripsi">Deskripsi Kegiatan</label>
            <div class="col-sm-9">              
              {{ form.deskripsi }}
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-3 col-form-label" for="id_tanggal_mulai">Tanggal Mulai</label>
            <div class="col-sm-9">
              {{ form.tanggal_mulai }}
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-3 col-form-label" for="id_tanggal_selesai">Tanggal Selesai</label>
            <div class="col-sm-9">
              {{ form.tanggal_selesai }}
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-3 col-form-label" for="id_deskripsi">Estimasi Biaya</label>
            <div class="col-sm-9">
              {{ form.jumlah_peturunan }}
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-3 col-form-label" for="id_tanggal_selesai">Batas Pembayaran</label>
            <div class="col-sm-9">
              {{ form.batas_pembayaran }}
            </div>
          </div>
        </form>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
          Tutup
        </button>
        <button type="submit" class="btn btn-primary" form="form">Simpan</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/detail_berita.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block extracss %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                      <h5 class="card-title" id="judulBerita">{{berita.judul.capitalize}}</h5>
                      <img class="card-img-top" src="{{berita.foto.url}}" alt="Card image cap" id="gambarBerita">
                      <p class="card-text" id="deskripsiBerita">{{berita.deskripsi}}</p>
                </div>
                <div class="card-footer">
                      <small class="text-muted" id="tanggalBerita">{{berita.tanggal}}</small>
                </div>
            </div>		
        </div>
    </div>
                
</div>
{% endblock %}

{% block extrajs %}
{% endblock %}

main/templates/main/kas.html
{% extends 'main/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
  <div class='mb-4 w-100 d-flex justify-content-between'>
    <div>
        <button type="button" class="btn btn-icon btn-primary mt-2" onclick="location.href='/acara/{{id_acara}}'">
            <i class="tf-icons bx bx-arrow-back"></i>
        </button>
    </div>
    <div> 
        {% if request.user.pengguna.tipe == 'Admin' or request.user.pengguna.tipe == 'Bendahara' %}
        <button type="button" class="btn btn-icon btn-primary mt-2" data-bs-toggle="modal" data-bs-target="#tambahKas">
            <span class="tf-icons bx bxs-plus-square"></span>
        </button>
        {% endif %}
        <button type="button" class="btn btn-icon btn-secondary mt-2"  onclick="frames['print_iframe'].print()">
            <i class='bx bx-printer'></i>
        </button>
        <a href="whatsapp://send?text=Berikut link data kas dadia:%0a%0a{{ request.build_absolute_uri }}%0a%0a_Pesan ini dibuat secara otomatis_" data-action="share/whatsapp/share"
            target="_blank"><button type="button" class="btn btn-icon btn-success mt-2"><i class='bx bxl-whatsapp' ></i></button></a>
    </div>
  </div>
  {% include 'main/messages.html'%}
  <iframe name="print_iframe" height=75% width="50%" src="{% url 'Print Kas' %}" style="display:none;">
  </iframe>
  <div class="card">
    <h3 class="card-header">Kas Dadia Pasek Gelgel</h3>
    <div class="table-responsive text-nowrap">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>No</th>
            <th>Tanggal</th>
            <th>Keterangan</th>
            <th>Pemasukan</th>
            <th>Pengeluaran</th>
            {% if request.user.pengguna.tipe == 'Admin' or request.user.pengguna.tipe == 'Bendahara' %}
            <th>Aksi</th>
            {% endif %}
          </tr>
        </thead>
        <tbody class="table-border-bottom-0">
          {% if ada_data %}
          {% for kas in semua_kas %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ kas.tanggal|date:"d-m-Y H:i" }}</td>
            <td class="text-wrap" style="min-width:300px">{{ kas.deskripsi }}</td>
            {% if kas.tipe == 'Pemasukan' %}
                <td align='right'>Rp. {{kas.jumlah|intcomma}}</td>
                <td align='right'></td>
            {% else %}
                <td align='right'></td>
                <td align='right'>Rp. {{kas.jumlah|intcomma}}</td>
            {% endif %}
            {% if request.user.pengguna.tipe == 'Admin' or request.user.pengguna.tipe == 'Bendahara' %}
            <td>
              {% if kas.status %}
                <button class="btn btn-icon btn-primary mx-1" onclick="ubah(url='{% url 'Get Kas' id=kas.id %}')" ><i class="bx bx-edit-alt"></i></button><button type="button" class="btn btn-icon btn-danger mx-1" onclick="confirm('Yakin ingin menghapus data ini?') ? location.href='{% url 'Hapus Kas' id=kas.id %}' : ''"><i class="tf-icons bx bx-trash"></i></button>
              {% endif %}
            </td>
            {% endif %}
          </tr>
          {% endfor %}
          {% else %}
            <td colspan="7"><p class="text-danger mb-0" align="center">Tidak Ada Data!</p></td>
          {% endif %}
          <tfoot class="table-border-bottom-0">
            <tr>
                <td colspan="3" align="center" class="fw-bolder">Jumlah</td>
                <td align='right'>Rp. {{jumlah_pemasukan|intcomma}}</td>
                <td align='right'>Rp. {{jumlah_pengeluaran|intcomma}}</td>
                {% if request.user.pengguna.tipe == 'Admin' or request.user.pengguna.tipe == 'Bendahara' %}
                <td></td>
                {% endif %}
            </tr>
            <tr>
                <td colspan="3" align="center" class="fw-bolder">Total Kas</td>
                {% if jumlah_pengeluaran > 0 %}
                <td colspan="2" align='right' class="text-success">Rp. {{total|intcomma}}</td>
                {% else %}
                <td colspan="2" align='right' class="text-danger">Rp. {{total|intcomma}}</td>
                {% endif %}
                {% if request.user.pengguna.tipe == 'Admin' or request.user.pengguna.tipe == 'Bendahara' %}
                <td></td>
                {% endif %}
            </tr>
          </tfoot>
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}
{% block modal %}
<div class="modal fade" id="tambahKas" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tambahKasLabel">Tambah Kas</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form id='form' action="#" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row mb-3">
            <input type="hidden" required="false" name="id_kas" id="id_kas"/>
            <label class="col-sm-3 col-form-label" for="id_tipe_dana">Tipe Kas</label>
            <div class="col-sm-9">
              {{ form.tipe }}
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-3 col-form-label" for="id_deskripsi">Keterangan Kas</label>
            <div class="col-sm-9">
              {{ form.deskripsi }}
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-3 col-form-label" for="id_jumlah">Jumlah Kas</label>
            <div class="col-sm-9">
              {{ form.jumlah }}
            </div>
          </div>
        </form>
        <a id="href_struk" href="" target="_blank"><img id="img_struk" class="w-100"/></a>
        <p class="text-danger" id="paragraph"></p>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
          Tutup
        </button>
        <button type="submit" name="btn" class="btn btn-primary" id="btn_submit" value="Tambah" form="form">Simpan</button>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

{% block extrajs %}
<script>
  let id_kas = document.getElementById('id_kas');
  let tipe = document.getElementById('id_tipe');
  let deskripsi = document.getElementById('id_deskripsi');
  let jumlah = document.getElementById('id_jumlah');
  let modal_label = document.getElementById('tambahKasLabel');
  let btn_submit = document.getElementById('btn_submit');

  function ubah(url) {
      $.ajax({
          url: url,
          success: function(data) {
              id_kas.value = JSON.parse(data)[0].pk
              data = JSON.parse(data)[0].fields
              tipe.value = data.tipe
              deskripsi.value = data.deskripsi
              jumlah.value = data.jumlah
              modal_label.innerText = 'Ubah Kas'
              btn_submit.innerText = "Simpan"
              btn_submit.value = "Ubah"
              $("#tambahKas").modal("show");
          }
      });
  }

  $('#tambahKas').on('hidden.bs.modal', function () {
      $(this).find('form').trigger('reset');
      id_kas.value = ""
      modal_label.innerText = 'Tambah Kas'
      btn_submit.innerText = "Simpan"
      btn_submit.value = "Tambah"
  })


</script>
{% endblock %}

main/templates/main/notifikasi.html
{% extends 'main/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
  {% include 'main/messages.html'%}
  <div class="card">
    <h3 class="card-header">Notifikasi Anda</h3>
    <div class="table-responsive text-nowrap">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>No</th>
            <th>Tanggal</th>
            <th>Dari</th>
            <th>Pesan</th>
          </tr>
        </thead>
        <tbody class="table-border-bottom-0">
          {% for notifikasi in semua_notifikasi %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ notifikasi.tanggal|date:"d-m-Y H:i" }}</td>
            <td>{{ notifikasi.dari.nama }}</td>
            <td class="text-wrap" style="min-width:300px">{{ notifikasi.pesan }}</td>
          </tr>
          {% endfor %}
          <tfoot class="table-border-bottom-0">
          </tfoot>
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

{% block modal %}
{% endblock %}

{% block extrajs %}
{% endblock %}